# Generated by Django 2.2.5 on 2019-12-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_auto_20191231_0229'),
        ('genre', '0002_auto_20191231_0229'),
        ('tag', '0001_initial'),
        ('users', '0003_auto_20190920_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='developer.Developer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='genre.Genre'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_tags',
            field=models.ManyToManyField(blank=True, to='tag.Tag'),
        ),
    ]
