# Generated by Django 2.2.5 on 2019-09-22 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scraper',
            new_name='Steam',
        ),
    ]
