# Generated by Django 2.2.5 on 2019-09-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0002_auto_20190922_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steam',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
