# Generated by Django 2.2.5 on 2019-09-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0003_auto_20190922_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steam',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
