# Generated by Django 2.2.5 on 2019-09-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0005_auto_20190922_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steam',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
