# Generated by Django 2.2.5 on 2019-09-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0008_auto_20190923_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steam',
            name='price',
            field=models.FloatField(),
        ),
    ]
