# Generated by Django 2.2.5 on 2019-09-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0009_auto_20190923_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steam',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
