# Generated by Django 2.2.5 on 2019-09-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0010_auto_20190923_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='steam',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
