# Generated by Django 2.2.5 on 2019-12-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0011_steam_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steam',
            name='gametitle',
            field=models.CharField(max_length=500),
        ),
    ]
