# Generated by Django 2.2.5 on 2019-12-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0012_auto_20191229_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='steam',
            name='developer',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='steam',
            name='genre',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
