# Generated by Django 2.2.5 on 2019-12-29 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0014_auto_20191229_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steam',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='genre.Genre'),
        ),
    ]
