# Generated by Django 2.2.5 on 2019-12-29 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0015_auto_20191229_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='steam',
            old_name='genre',
            new_name='genre_id',
        ),
    ]
