# Generated by Django 2.2.5 on 2019-12-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0016_auto_20191229_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steam',
            name='genre_id',
        ),
        migrations.AddField(
            model_name='steam',
            name='genre',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
