# Generated by Django 2.2.5 on 2019-12-29 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
        ('steam', '0017_auto_20191229_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steam',
            name='genre',
        ),
        migrations.AddField(
            model_name='steam',
            name='genre_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='genre.Genre'),
        ),
    ]
