# Generated by Django 2.2.5 on 2019-12-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0018_auto_20191229_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steam',
            name='tag',
            field=models.CharField(max_length=500),
        ),
    ]
