# Generated by Django 2.2.5 on 2019-12-29 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0019_auto_20191229_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='steam',
            old_name='genre_id',
            new_name='genre',
        ),
    ]
