# Generated by Django 2.2.5 on 2019-12-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0022_auto_20191229_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nametest', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='steam',
            name='test',
            field=models.ManyToManyField(null=True, to='steam.Test'),
        ),
    ]
