# Generated by Django 2.2.5 on 2019-12-30 09:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('steam', '0023_auto_20191230_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='steam',
            options={'ordering': ['gametitle']},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['nametest']},
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
