# Generated by Django 2.2.5 on 2019-12-30 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0024_auto_20191230_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steam',
            name='test',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
