# Generated by Django 2.2.5 on 2019-12-30 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0025_auto_20191230_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steam',
            name='tags',
        ),
    ]
