# Generated by Django 2.2.5 on 2019-12-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('steam', '0026_remove_steam_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='steam',
            name='tags',
            field=models.ManyToManyField(null=True, to='tag.Tag'),
        ),
    ]
