# Generated by Django 2.2.5 on 2019-12-31 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('steam', '0028_auto_20191231_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, choices=[(10, '**********'), (9, '*********'), (8, '********'), (7, '*******'), (6, '******'), (5, '*****'), (4, '****'), (3, '***'), (2, '**'), (1, '*')])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steam.Steam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
