# Generated by Django 2.2.5 on 2020-01-15 15:29

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0030_auto_20200115_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steam',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='FYP/django/rise/game_pics'), upload_to=''),
        ),
    ]
