# Generated by Django 2.2.5 on 2019-09-19 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraper',
            name='image1',
        ),
    ]
