# Generated by Django 2.2.5 on 2019-09-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0002_remove_scraper_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='image1',
            field=models.ImageField(default='', editable=False, upload_to=''),
        ),
    ]
