# Generated by Django 2.2.5 on 2019-09-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0003_scraper_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='url1',
            field=models.TextField(default='', editable=False),
        ),
    ]
