# Generated by Django 2.2.5 on 2019-09-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0005_auto_20190920_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='image1',
            field=models.ImageField(editable=False, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='url1',
            field=models.TextField(editable=False),
        ),
    ]
