# Generated by Django 2.2.5 on 2019-09-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0006_auto_20190920_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='image1',
            field=models.ImageField(upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='url1',
            field=models.TextField(),
        ),
    ]
